minio:
  bucket:
    store: yout-back
  url: http://localhost:9000
  access-key: artur
  secret-key: ***REMOVED***

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
logging:
  level:
    com:
      artur: TRACE
    org:
      apache: INFO
server:
  port: 8082

