object-storage:
  root-folder: yout-back
  url: http://${OBJECT_STORAGE_HOST:localhost}:9000
  access-key: ${OBJECT_STORAGE_ACCESS:admin}
  secret-key: ${OBJECT_STORAGE_SECRET:adminadmin}

spring:
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:localhost}:9093
logging:
  level:
    com:
      artur: TRACE
    org:
      apache: INFO
server:
  port: 8081

