minio:
  bucket:
    store: yout-back
  url: http://${MINIO_HOST:localhost}:9000
  access-key: ${MINIO_ACCESS:admin}
  secret-key: ${MINIO_SECRET:adminadmin}

spring:
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:localhost}:9093
logging:
  level:
    com:
      artur: TRACE
    org:
      apache: INFO
server:
  port: 8081

