minio:
  bucket:
    store: yout-back
  url: http://minio:9000
  access-key: ${MINIO_ACCESS:artur}
  secret-key: ${MINIO_SECRET:adminadmin}

spring:
  kafka:
    bootstrap-servers: "http://kafka:9092"
logging:
  level:
    com:
      artur: TRACE
    org:
      apache: INFO
server:
  port: 8081

